version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      cooldown: default-days
    insecure-external-code-execution: deny
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      cooldown: default-days
    insecure-external-code-execution: deny
